### ISSUE TITLE
Join the discussion of RFC for Relay Fuzzer

### ISSUE THREAD

**Issue by ganler** [wzh99/GenCoG#1]
Hi, there is an RFC regarding doing fuzzing at Relay level on TVM Discuss: https://discuss.tvm.apache.org/t/rfc-type-directed-relay-fuzzing-library/ 

`GenCoG` is a very related project so it would be great if you can join our discussion for better shaping the fuzzer! Thanks!

**Comment by wzh99** [comment]
@ganler Thanks for inviting me to the discussion. I am pleased to share my observation and experience there.

**Comment by ganler** [comment]
Thanks!
